### ISSUE TITLE
MS Learn Module Update Request: [REPLACE_WITH_MODULE_TITLE]

### ISSUE THREAD

**Issue by Dolly03s** [githubpartners/microsoft-learn#126]
### Which of the MS Learn modules from the dropdown are you submitting an update request?

None

### Additional information

- [x] Fix a broken user experience (broken links, exercise error, etc.)
- [x] Update incorrect information
- [x] Add new content to the module
- [x] Some other request

```[tasklist]
### Tasks
- [ ] https://github.com/githubpartners/microsoft-learn/issues/120
- [ ] https://github.com/githubpartners/microsoft-learn/issues/119
```

**Comment by rmallorybpc** [comment]
Hi @Dolly03s ,

Thank you for reporting the issue. We are closing this issue due to the length of time open. Please let us know if the issue still exists by reporting an updated issue.
